/**
 * Centralized UI copy (English).
 * Structured for future i18n.
 * Components never inline raw strings — always use these constants.
 */

export const copy = {
  // App titles and headers
  appTitle: 'FPL Squad Viewer',
  appSubtitle: 'See your FPL squad and points - just enter your team ID',

  startupMaintenanceTitle: 'We’re updating',
  startupMaintenanceBody:
    'Loading the latest squad and lineup data. You’ll be able to use the app again in a few minutes.',
  startupMaintenanceProgressLabel: 'Startup progress',

  // Entry screen
  entryHeadlineLine1: 'Your squad.',
  entryHeadlineAccent: 'Every gameweek.',
  entryHelper: 'Find your team ID in the FPL URL: fantasy.premierleague.com/entry/{ID}/event/{GW}',
  entryInputLabel: 'Team ID',
  entryInputPlaceholder: 'Enter your team ID',
  entrySubmit: 'View squad',

  // Entry validation
  entryErrorEmpty: 'Please enter a team ID',
  entryErrorInvalid: 'Team ID must be a positive number',
  entryErrorNotFound: "We couldn't find a team with that ID. Please check and try again.",
  entryErrorUnreachable: "Couldn't reach the FPL servers. Please try again.",

  // Sign in screen
  signInHeadline: 'Sign In',
  signInSubtitle: 'Access your FPL dashboard',
  signInEmailLabel: 'Email',
  signInEmailPlaceholder: 'you@example.com',
  signInPasswordLabel: 'Password',
  signInPasswordPlaceholder: 'Password',
  signInSubmit: 'Sign In',
  signInGoogle: 'Sign in with Google',
  signInDivider: 'or',
  signInNoAccount: "Don't have an account?",
  signInSignUp: 'Sign up',
  signInTryDemo: 'Try Demo',
  signInForgotPassword: 'Forgot password?',
  signInPasswordResetBanner: 'Password updated — sign in with your new password.',

  // Forgot password screen
  forgotPasswordHeadline: 'Forgot password?',
  forgotPasswordSubtitle: "Enter your email and we'll send you a reset link.",
  forgotPasswordEmailLabel: 'Email',
  forgotPasswordEmailPlaceholder: 'you@example.com',
  forgotPasswordSubmit: 'Send reset link',
  forgotPasswordBackToSignIn: 'Back to Sign In',
  forgotPasswordSuccessMessage: 'Check your inbox — we sent a reset link to {email}.',
  forgotPasswordError: 'Something went wrong. Please try again.',

  // Reset password screen
  resetPasswordHeadline: 'Set new password',
  resetPasswordSubtitle: 'Choose a strong password for your account.',
  resetPasswordNewLabel: 'New password',
  resetPasswordNewPlaceholder: 'New password',
  resetPasswordConfirmLabel: 'Confirm password',
  resetPasswordConfirmPlaceholder: 'Confirm password',
  resetPasswordSubmit: 'Update password',
  resetPasswordMismatchError: "Passwords don't match.",
  resetPasswordInvalidToken: 'This reset link is invalid or has expired.',
  resetPasswordRequestNew: 'Request a new one',
  resetPasswordError: 'Something went wrong. Please try again.',
  resetPasswordBackToSignIn: 'Back to sign in',

  // Demo gate dialog
  demoGateTitle: 'Sign in to unlock',
  demoGateBody: 'All features are available after creating a free account. Your demo session is saved.',
  demoGateSignIn: 'Sign In',
  demoGateSignUp: 'Create Account',
  demoGateDismiss: 'Dismiss',

  // Verify email sheet / screen
  verifyEmailHeadline: 'Check your inbox',
  verifyEmailBody: 'We sent a verification link to {email}. Open it to activate your account.',
  verifyEmailResend: 'Resend email',
  verifyEmailResent: 'Email sent!',
  verifyEmailWrongEmail: 'Wrong email? Sign up again',
  signInUnverifiedEmailError: "Your email hasn't been verified yet. Check your inbox for the link we sent when you signed up.",

  // Sign up screen
  signUpHeadline: 'Create Account',
  signUpSubtitle: 'Join FPL Squad Viewer',
  signUpNameLabel: 'Name',
  signUpNamePlaceholder: 'Your name',
  signUpEmailLabel: 'Email',
  signUpEmailPlaceholder: 'you@example.com',
  signUpPasswordLabel: 'Password',
  signUpPasswordPlaceholder: 'Password',
  signUpSubmit: 'Create Account',
  signUpGoogle: 'Sign up with Google',
  signUpDivider: 'or',
  signUpHaveAccount: 'Already have an account?',
  signUpSignIn: 'Sign in',

  // Squad screen
  squadGameweekLabel: 'GW',
  squadLoadError: "Couldn't load this GW",
  squadRetry: 'Try again',
  squadEmpty: 'No squad available for GW {GW}',
  squadEmptyHeading: 'No squad yet',
  squadEmptySubtext:
    'No squad available for GW {GW}. Use the arrows to jump to a later GW.',
  squadJumpToCurrent: 'Jump to current GW →',
  squadNotFound: "We couldn't find a team with that ID. Please check and try again.",

  // Active chips
  chipActiveSuffix:   'ACTIVE',
  chipWildcard:       'Wildcard',
  chipTripleCaptain:  'Triple Captain',
  chipFreeHit:        'Free Hit',
  chipBenchBoost:     'Bench Boost',

  // Summary strip
  summaryTotal: 'TOTAL',
  summaryAverage: 'AVERAGE',
  summaryHighest: 'HIGHEST',
  summaryRank: 'RANK',
  summaryTransfers: 'TRANSFERS',
  summaryPlaceholder: '-',

  // Positions
  positionGK: 'GK',
  positionDEF: 'DEF',
  positionMID: 'MID',
  positionFWD: 'FWD',

  // Player status
  statusCaptain: 'C',
  statusViceCaptain: 'V',
  statusDoubtful: 'Doubtful',
  statusInjured: 'Injured',
  statusSuspended: 'Suspended',
  statusUnavailable: 'Unavailable',

  // Loading states
  loadingPlaceholder: 'Loading...',

  // Common actions
  closeButton: 'Close',

  // Drawer account actions
  drawerChangeTeam: 'Change your team ID',
  drawerSignOut: 'Sign out',

  // Team info panel
  teamInfoOverallPts: 'Overall pts',
  teamInfoOverallRank: 'Overall rank',
  teamInfoGwPts: 'GW pts',
  teamInfoTotalPlayers: 'Total players',
  teamInfoGwHistory: 'My GW history',
  squadNavLink: 'My Squad',
  teamInfoDrawerLabel: 'Team information',
  teamInfoOpenDrawer: 'Open team info',

  donationBannerTitle: 'Support the project',
  donationBannerSubtitle: 'Donate via Monobank',

  // Gameweek history screen
  historyTitle: 'My GW history',
  historyThisSeason: 'This Season',
  historyColGW: 'GW',
  historyColOR: 'OR',
  historyColOP: 'OP',
  historyColGWR: 'GWR',
  historyColGWP: 'GWP',
  historyColPB: 'PB',
  historyColTM: 'TM',
  historyColTC: 'TC',
  historyColValue: '£m',
  historyEmpty: 'No GWs played yet',
  historyLoadError: "Couldn't load GW history",
  historyRetry: 'Try again',
  historyBack: 'Squad',
  squadBackToHistory: 'History',

  // Leagues stats screen
  statsTitle: 'My Stats',
  statsTabLeagues: 'Leagues',
  statsTabHistory: 'My GW history',
  statsBack: 'Squad',
  statsGeneralLeagues: 'General Leagues',
  statsH2HLeagues: 'Head-to-Head Leagues',
  statsNoLeagues: 'No leagues found',
  statsLoadError: "Couldn't load league standings",
  statsRetry: 'Try again',
  statsMyStats: 'My Stats',

  // League standings screen
  leagueStandingsBack: 'Leagues',
  leagueStandingsLoadError: 'Could not load league standings.',
  leagueStandingsRetry: 'Retry',
  leagueStandingsEmpty: 'No participants found.',
  leagueStandingsLoadMore: 'Load more',
  leagueStandingsLoading: 'Loading…',

  // Team of the Week screen
  teamOfTheWeekTitle: 'Team of the Week',
  teamOfTheWeekBack: 'Squad',
  teamOfTheWeekLoadError: "Couldn't load the Team of the Week",
  teamOfTheWeekRetry: 'Try again',
  teamOfTheWeekNotAvailable: 'Team of the Week not available yet for this GW',
  teamOfTheWeekNavLink: 'Team of the Week',

  // Top Players screen
  topPlayersTitle: 'Top Players',
  topPlayersBack: 'Squad',
  topPlayersTabGw: 'This GW',
  topPlayersTabSeason: 'Season',
  topPlayersLoadError: "Couldn't load top players",
  topPlayersRetry: 'Try again',
  topPlayersNavLink: 'Top Players',

  // Leaderboard screen
  leaderboardNavLink: 'DEFCON/BPS leaders',
  leaderboardBack: 'Squad',
  leaderboardLoadError: 'Failed to load leaderboard',
  leaderboardRetry: 'Retry',
  priceChangesNavLink: 'Price changes',
  priceChangesTitle: 'Price changes',
  priceChangesActualTab: 'Actual',
  priceChangesTonightTab: 'Tonight',
  priceChangesAllFpl: 'All FPL',
  priceChangesMySquad: 'My squad',
  priceChangesThisGw: 'This GW',
  priceChangesSeason: 'Season',
  priceChangesRisers: 'Risers',
  priceChangesFallers: 'Fallers',
  priceChangesLikelyRise: 'Likely rise',
  priceChangesLikelyFall: 'Likely fall',
  priceChangesPremiumTitle: 'My squad price view',
  priceChangesPremiumDescription:
    'See price changes and tonight predictions for your 15 players only. Upgrade to Premium.',
  priceChangesPremiumFreeLabel: 'All FPL lists',
  priceChangesPremiumPremiumLabel: 'My squad lens',
  priceChangesDisclaimer:
    'Tonight predictions are estimates based on transfer activity, not official FPL data.',
  priceChangesEmptyGw: 'No price changes this gameweek yet. Updates usually appear overnight (UK).',
  priceChangesEmptySeason: 'No season price movement for this filter.',
  priceChangesEmptyTonight: 'No players currently projected to move for this filter.',
  priceChangesEmptySquad: 'None of your players match this filter.',
  priceChangesProfileGw: 'GW{n} — {pts} pts',
  priceChangesLikelihoodVeryLikely: 'Very likely',
  priceChangesLikelihoodLikely: 'Likely',
  priceChangesTransfersIn: '{n} in',
  priceChangesTransfersOut: '{n} out',
  priceChangesTransferInPct: '{n}% in',
  priceChangesLoadError: 'Could not load price data.',
  priceChangesRetry: 'Retry',
  priceChangesFilterAll: 'All',
  priceChangesFilterGK: 'GK',
  priceChangesFilterDEF: 'DEF',
  priceChangesFilterMID: 'MID',
  priceChangesFilterFWD: 'FWD',
  priceChangesUnlockSquad: 'Unlock my squad view',

  // Predicted Points screen (PRED-02)
  predictedPointsNavLink: 'Predicted Points',
  predictedPointsTitle: 'Predicted Points',
  predictedPointsGwLabel: 'GW {n}',
  predictedPointsXptsLabel: 'xPts',
  predictedPointsUnlockLabel: 'Unlock all predictions',
  predictedPointsPremiumTitle: 'See all predicted points',
  predictedPointsPremiumDescription:
    'Subscribe to unlock the full ranked list — all players per position for the next gameweek.',
  predictedPointsPremiumFreeLabel: 'Top 3 per position',
  predictedPointsPremiumPremiumLabel: 'Full ranked list',
  predictedPointsEmptyPosition: 'No prediction data available for this position.',
  predictedPointsDisclaimer:
    'Approximate statistical estimates, not official FPL data or betting advice.',
  predictedPointsFplFallback:
    'Showing FPL expected points until model estimates are ready for this gameweek.',
  predictedPointsXGLabel: 'xG',
  predictedPointsXALabel: 'xA',
  predictedPointsCSLabel: 'CS',
  predictedPointsDefconLabel: 'DC',
  predictedPointsConfidenceLow: 'Low',
  predictedPointsConfidenceMedium: 'Med',
  predictedPointsConfidenceHigh: 'High',
  predictedPointsBreakdownAria: 'Expected goals, assists, clean sheet, and defensive contribution',
  predictedLineupsNavLink: 'Predicted Lineups',
  predictedLineupsTitle: 'Predicted Lineups',
  predictedLineupsGwLabel: 'GW {n}',
  predictedLineupsFormationLabel: 'Formation',
  predictedLineupsTableView: 'Table',
  predictedLineupsPitchView: 'Pitch',
  predictedLineupsColumnName: 'Player',
  predictedLineupsColumnXMins: 'xMins',
  predictedLineupsXMinsPill: 'exp {n} min',
  predictedLineupsXMinsAria: 'Expected minutes {n}',
  predictedLineupsPlayRiskAria: 'May not start — open for details',
  predictedLineupsBenchRisk: 'Rotation risk',
  predictedLineupsInjuryWarning: 'Injury doubt',
  predictedLineupsEmptyTeam: 'No lineup data for this team.',
  predictedLineupsLoadError: 'Could not load predicted lineups.',
  predictedLineupsRetry: 'Try again',
  predictedLineupsUnlockLabel: 'Unlock projected lineups',
  predictedLineupsPremiumTitle: 'See predicted lineups',
  predictedLineupsPremiumDescription:
    'View projected starting elevens and formations for all 20 Premier League clubs before each deadline.',
  predictedLineupsPremiumFreeLabel: 'Not available on free tier',
  predictedLineupsPremiumPremiumLabel: 'All clubs · table & pitch',
  predictedLineupsVsHome: 'vs {opponent} (H)',
  predictedLineupsVsAway: 'vs {opponent} (A)',

  topPlayersTabTeam: 'By Team',
  topPlayersTabTotw: 'TOTW',
  topPlayersTeamSelectLabel: 'Select team',
  topPlayersTeamLoadError: "Couldn't load team players",

  // Transfer planner screen
  transfersBack: 'Squad',
  transfersTitle: 'Transfers',
  transfersNavLink: 'Transfer Planner',
  transfersBank: 'Bank',
  transfersFree: 'Free',
  transfersCost: 'Cost',
  transfersWildcard: 'WC',
  transfersFreeHit: 'FH',
  transfersBenchBoost: 'BB',
  transfersTripleCaptain: 'TC',
  transfersWildcardActive: 'Wildcard active',
  transfersFreeHitActive: 'Free Hit active — squad reverts after GW{n}',
  transfersFreeHitActiveFinal: 'Free Hit active',
  transfersBenchBoostActive: 'Bench Boost — transfers cost normally',
  transfersTripleCaptainActive: 'Triple Captain — transfers cost normally',
  chipUsedAriaLabel: 'Already played',
  chipBlockedUsed:   '{name} already played in GW{gw}',
  chipBlockedNoGw:   '{name} already played this season',
  transfersPendingTitle: 'Planned transfers',
  transfersPendingEmpty: 'Tap a player to start planning',
  transfersReset: 'Reset',
  transfersSavePlan: 'Save Plan',
  transfersUndoSwap: 'Undo',
  transfersFreeEditable: 'Free transfers (tap to edit)',
  transfersLoadError: "Couldn't load transfers data",
  transfersRetry: 'Try again',
  transfersNoSquad: 'No squad found — play at least one gameweek to use the transfer planner',
  transfersBudgetDisclaimer:
    "Selling prices are approximate. The actual price may differ if a player's value changed since you bought them.",
  transfersPickerTitle: 'Replace {name}',
  transfersPickerSubtitle: '{position} · selling for £{cost}m',
  transfersPickerSearch: 'Search players…',
  transfersSortPts: 'Pts',
  transfersSortPrice: 'Price',
  transfersSortForm: 'Form',
  transfersSortGwPts: 'GW pts',
  transfersSortSel: 'OWN%',
  transfersSortXPts: 'xPts',
  transfersAlreadyThree: '3 already',
  transfersNFree: '{n} of {m} free used',
  transfersSavedToast: 'Plan saved',
  transfersStaleToast: 'Your saved plan was for GW{n} which has passed. Starting fresh.',
  transfersSortButton: 'Sort',
  transfersPositionAll: 'ALL',
  transfersColPlayer: 'Player',
  transfersColFix: 'Fix',
  transfersColOwnership: 'OWN%',
  transfersColOwnershipTitle: 'Ownership percentage',
  transfersColPts: 'Pts',
  transfersColXPts: 'xPts',
  transfersColCost: 'Cost',

  // Player info popup
  playerInfoOpen: 'Player info',
  playerInfoUpcomingFixtures: 'Upcoming Fixtures',

  // View toggle
  viewPitch: 'Pitch',
  viewList: 'List',
  viewToggleLabel: 'View mode',

  // List view section headers
  listGroupGK: 'Goalkeeper',
  listGroupDEF: 'Defenders',
  listGroupMID: 'Midfielders',
  listGroupFWD: 'Forwards',
  listGroupBench: 'Bench',

  // List view column headers
  listColPts: 'Pts',
  listColMP: 'MP',
  listColGS: 'GS',
  listColA: 'A',
  listColCS: 'CS',
  listColGC: 'GC',
  listColOG: 'OG',
  listColPS: 'PS',
  listColPM: 'PM',
  listColYC: 'YC',
  listColRC: 'RC',
  listColS: 'S',
  listColBonus: 'Bonus',

  // List view column legend (full names)
  listLegendHeading: 'Key',
  listLegendPts: 'Points',
  listLegendMP: 'Minutes played',
  listLegendGS: 'Goals scored',
  listLegendA: 'Assists',
  listLegendCS: 'Clean sheets',
  listLegendGC: 'Goals conceded',
  listLegendOG: 'Own goals',
  listLegendPS: 'Penalties saved',
  listLegendPM: 'Penalties missed',
  listLegendYC: 'Yellow cards',
  listLegendRC: 'Red cards',
  listLegendS: 'Saves',
  listLegendBonus: 'Bonus points',

  // Guest squad view (viewing another manager's team)
  squadGuestBack: 'Back',

  // Watchlist screen
  watchlistTitle: 'Managers Watchlist',
  watchlistBack: 'Squad',
  watchlistNavLink: 'Managers Watchlist',
  watchlistCapacity: '{n}/{max} following',
  watchlistEmptyHeading: 'No managers followed yet',
  watchlistEmptySubtext: 'Add managers below to track their GW performance.',
  watchlistAddInputPlaceholder: 'Enter team ID…',
  watchlistAddButton: 'Follow',
  watchlistAddValidating: 'Checking…',
  watchlistAddConfirm: 'Follow {name}?',
  watchlistAddConfirmButton: 'Confirm',
  watchlistAddCancelButton: 'Cancel',
  watchlistAddErrorNotFound: 'Team not found. Check the ID and try again.',
  watchlistAddErrorNetwork: "Couldn't reach FPL servers. Try again.",
  watchlistAddDuplicate: 'Already following this manager.',
  watchlistAddLimit: 'Watchlist full ({max}/{max}). Remove a manager to add another.',
  watchlistRemoveAriaLabel: 'Unfollow {name}',
  watchlistFollowButton: 'Follow',
  watchlistFollowingButton: 'Following',
  watchlistUnfollowButton: 'Unfollow',
  watchlistFollowLimitToast: 'Watchlist full ({max}/{max}).',
  watchlistFromLeaguesHeading: 'From My Leagues',
  watchlistFromLeaguesNoTeam: 'Open your squad first to browse your leagues.',
  watchlistFromLeaguesLoadError: "Couldn't load leagues.",
  watchlistFromLeaguesStandingsLoadError: "Couldn't load standings.",
  watchlistFromLeaguesLoadMore: 'Load more',
  watchlistColManager: 'Manager',
  watchlistColGwPts: 'GW',
  watchlistColGwRank: 'GW Rk',
  watchlistColOverallRank: 'OR',
  watchlistColRankDelta: 'Δ Rank',
  watchlistColTransfers: 'Transfers made',
  watchlistColCaptain: 'Cap',
  watchlistColViceCaptain: 'VC',
  watchlistColLatestIn: 'In',
  watchlistColXfrCost: 'Transfer fee',
  watchlistColSquadValue: 'Squad',
  watchlistColBank: 'Bank',
  watchlistTransferCostFree: 'Free',
  watchlistUnfollow: 'Unfollow',
  watchlistLoadError: 'Failed to load',
  watchlistRowErrorRemove: 'Remove',

  // Premium gate sheet
  premiumSheetUpgrade: 'Upgrade to Premium',
  premiumSheetComingSoon: 'Coming soon',
  premiumSheetDismiss: 'Maybe later',
  premiumSheetFreeTier: 'Free',
  premiumSheetPremiumTier: 'Premium ✦',
  premiumWatchlistTitle: 'Follow more managers',
  premiumWatchlistDescription: "You've reached the free plan limit. Upgrade to track more managers and unlock features.",
  premiumWatchlistFreeLabel: '2 managers',
  premiumWatchlistPremiumLabel: '10 managers',

  premiumPlayerWatchlistTitle: 'Follow more players',
  premiumPlayerWatchlistDescription: "You've reached the free plan limit. Upgrade to track more players and unlock features.",
  premiumPlayerWatchlistFreeLabel: '2 players',
  premiumPlayerWatchlistPremiumLabel: '15 players',

  premiumUpsellCta: 'Get Premium',
  premiumUpsellDismiss: 'Not this gameweek',
  premiumUpsellClose: 'Close',
  premiumUpsellAriaLabel: 'Premium upgrade offer',
  premiumUpsellTransferTitle: "Don't leave points on the table",
  premiumUpsellTransferLead:
    "Your rivals are already using projections and chip timing — you're still guessing.",
  premiumUpsellTransferBenefit1:
    "Every player's predicted points for the next GW — not just the obvious top 3",
  premiumUpsellTransferBenefit2:
    'Know when to Wildcard, Free Hit, Bench Boost or Triple Captain — not just whether',
  premiumUpsellTransferBenefit3:
    'Track 10 managers and 15 players on your watchlist while you plan moves',
  premiumUpsellTransferPremium: "Premium: every player's xPts · 10 managers · 15 players",
  premiumUpsellPredictionsTitle: "The haulers aren't in the top 3",
  premiumUpsellPredictionsLead:
    "The differentials that win mini-leagues sit further down the list — you can't see them on free.",
  premiumUpsellPredictionsBenefit1: 'Full xPts ranking for every player before the deadline',
  premiumUpsellPredictionsBenefit2:
    'Spot price rises and template traps before they hit your rank',
  premiumUpsellPredictionsBenefit3: "Projected lineups so you don't captain a bench risk",

  // Transfer help tour
  tourHelpButton: 'Open tour',
  tourSkip: '✕ Skip',
  tourNext: 'Next',
  tourBack: 'Back',
  tourFinish: 'Got it!',
  tourStep1Title: 'Chip Badges',
  tourStep1Text: 'Wildcard (WC) and Free Hit (FH) allow unlimited transfers. Bench Boost (BB) and Triple Captain (TC) provide scoring bonuses.',
  tourStep2Title: 'Bank & Cost',
  tourStep2Text: 'Track your remaining budget, available free transfers, and the point cost of your planned moves.',
  tourStep4Title: 'Player Stats',
  tourStep4Text: 'View ownership and other key stats to help you decide on transfers.',
  tourStep5Title: 'Fixture Difficulty',
  tourStep5Text: 'Colour-coded chips show the next opponent. Green is easy, maroon is hard (FDR 1-5).',
  tourStep6Title: 'Substitutions',
  tourStep6Text: 'Use the swap icon to move players between your starting XI and the bench.',
  tourStep9Title: 'Save Your Plan',
  tourStep9Text: "These players only score if a starter doesn't play. Order matters for auto-subs! Reset clears your draft. Save Plan stores it to your account for later.",

  // Gameweek review screen
  reviewTitle: 'GW Review',
  reviewBack: 'Squad',
  reviewNavLink: 'Last GW Review',
  reviewGwPts: 'GW points',
  reviewVsAvg: 'vs avg',
  reviewAvg: 'avg',
  reviewHighest: 'highest',
  reviewGwRank: 'GW rank',
  reviewPlayersSection: 'Players — sorted by points',
  reviewBenchSection: 'Bench',
  reviewBenchWasted: '{pts} points left on bench',
  reviewBenchNone: 'Nothing left on bench',
  reviewNoAutosubs: 'No automatic substitutions',
  reviewBenchDivider: 'Bench',
  reviewTransfersSection: 'Transfers this GW',
  reviewNoTransfers: 'Rolled transfer — squad unchanged',
  reviewTransferOut: 'OUT',
  reviewTransferIn: 'IN',
  reviewTransferHit: '−{cost} pts transfer hit',
  reviewWhatIfSection: 'What if you made no transfers?',
  reviewWhatIfActual: 'Your score',
  reviewWhatIfWithTransfers: 'with transfers',
  reviewWhatIfHypothetical: 'Without transfers',
  reviewWhatIfGain: 'Transfers gained you {n} points',
  reviewWhatIfLoss: 'Transfers cost you {n} points',
  reviewWhatIfBreakEven: 'Transfers broke even this week',
  reviewLoadError: "Couldn't load gameweek review",
  reviewRetry: 'Try again',
  reviewNoGw: 'No completed GWs yet',

  // Player Watchlist screen
  playerWatchlistTitle: 'Player Watchlist',
  playerWatchlistBack: 'Back',
  playerWatchlistEmpty: 'No players followed yet.',
  playerWatchlistEmptySubtext: 'Tap ★ on any player to start tracking them.',
  playerWatchlistBrowse: 'Browse Top Players',
  playerWatchlistAddByName: '＋ Add player by name',
  playerWatchlistSearch: 'Search watched players…',
  playerWatchlistCapacityBadge: '{count}/{limit} following',
  playerWatchlistFull: 'Watchlist full ({limit}/{limit})',
  playerWatchlistFollow: 'Follow',
  playerWatchlistUnfollow: 'Unfollow',
  playerWatchlistAddSheetTitle: 'Add player',
  playerWatchlistAddSearch: 'Search players…',
  playerWatchlistNavLink: 'Player Watchlist',
  playerWatchlistRemove: 'Unfollow player',

  fixturesCalendarNavLink: 'Fixtures',
  fixturesCalendarTitle: 'Fixtures Calendar',
  fixturesCalendarTabOfficial: 'Official',
  fixturesCalendarTabOverall: 'Overall',
  fixturesCalendarTabDefensive: 'Defensive',
  fixturesCalendarTabAttacking: 'Attacking',
  fixturesCalendarTabRestDays: 'Rest Days',
  fixturesCalendarRestDaysTbc: 'TBC',
  fixturesCalendarHelpButton: 'Open help',
  fixturesCalendarHelpTitle: 'Fixtures calendar guide',
  fixturesCalendarHelpIntro:
    'Teams are rows and gameweeks are columns. Scroll horizontally through all 38 gameweeks; the current gameweek has a dot under its number.',
  fixturesCalendarHelpCell:
    'Each cell shows the opponent code on the top line. On fixture tabs the second line is H (home) or A (away).',
  fixturesCalendarHelpTabsHeading: 'Tabs',
  fixturesCalendarHelpTabOfficial: "Official — FPL's own fixture difficulty rating.",
  fixturesCalendarHelpTabOverall: 'Overall — opponent strength normalised to 1–5.',
  fixturesCalendarHelpTabDefensive:
    'Defensive — opponent attack strength; best for goalkeepers and defenders.',
  fixturesCalendarHelpTabAttacking:
    'Attacking — opponent defence strength; best for midfielders and forwards.',
  fixturesCalendarHelpTabRestDays:
    "Rest Days — days since the team's previous kick-off. Short gaps mean higher rotation risk.",
  fixturesCalendarHelpSpecialHeading: 'Special cells',
  fixturesCalendarHelpDgw: 'Double gameweek: two opponent chips side by side in one cell.',
  fixturesCalendarHelpBgw: 'Blank gameweek: a dash (—) when the team has no fixture.',
  fixturesCalendarHelpFdrHeading: 'Fixture difficulty colours',
  fixturesCalendarHelpFdr1: 'Very easy',
  fixturesCalendarHelpFdr2: 'Easy',
  fixturesCalendarHelpFdr3: 'Medium',
  fixturesCalendarHelpFdr4: 'Hard',
  fixturesCalendarHelpFdr5: 'Very hard',
  fixturesCalendarHelpRestHeading: 'Rest days colours',
  fixturesCalendarHelpRestTight: '3 days or less — tight turnaround',
  fixturesCalendarHelpRestModerate: '4–6 days between matches',
  fixturesCalendarHelpRestEasy: '7 days or more',
  fixturesCalendarHelpRestTbc: 'Kick-off not yet announced',
};

/**
 * Interpolate copy strings.
 * Usage: interpolate(copy.squadEmpty, { GW: '15' })
 */
export function interpolate(template: string, values: Record<string, string | number>): string {
  return template.replace(/{(\w+)}/g, (_, key) => String(values[key] ?? ''));
}
